// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vault} from '../models';

export function LoadDefaultVault():Promise<vault.Snapshot>;

export function OpenVault():Promise<vault.Snapshot>;
