// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadDefaultVault() {
  return window['go']['main']['App']['LoadDefaultVault']();
}

export function OpenVault() {
  return window['go']['main']['App']['OpenVault']();
}
